domain_file: domains.txt
smtp:
  smtp_server: smtp.example.com
  smtp_port: 587
  use_tls: true
  sender_email: your_email@example.com
  recipient_email: recipient_email@example.com
  username: your_username
  password: your_password
warning_threshold: 30
critical_threshold: 10
